#- script: /some/local/script.sh --some-arguments 1234
- hosts: Masters #Sample
  remote_user: build
  become: True
  become_method: sudo
  become_user: root
  gather_facts: force
  tasks:
    - name: Config Hadoop master
      copy: src=etc/hadoop/{{ item }} dest=/usr/local/hadoop/etc/hadoop/{{ item }}
      with_items:
        - slaves
        - mapred-site.xml
