- hosts: All #Sample
  remote_user: ubuntu
  become: True
  become_method: sudo
  become_user: root
  gather_facts: force
  tasks:
    - name: Install Kafka
      script: util/kafka.sh
    - name: Add Kafka HOME into bashrc
      lineinfile:
        dest="/home/{{ item }}/.bashrc"
        line="export KAFKA_HOME=/usr/local/kafka"
        state=present
        owner={{ item }}
        mode=0644
      with_items:
        - ubuntu
    - name: Add PATH into bashrc
      lineinfile:
        dest="/home/{{ item }}/.bashrc"
        line="export PATH=$PATH:$KAFKA_HOME/bin"
        state=present
        owner={{ item }}
        mode=0644
      with_items:
        - ubuntu
