#- script: /some/local/script.sh --some-arguments 1234
- hosts: All #Sample
  remote_user: build
  become: True
  become_method: sudo
  become_user: root
  gather_facts: force
  tasks:
    - name: Install Hadoop
      script: util/hadoop.sh
    - name: Add Hadoop HOME into bashrc
      lineinfile:
        dest="/home/{{ item }}/.bashrc"
        line="export HADOOP_HOME=/usr/local/hadoop"
        state=present
        owner={{ item }}
        mode=0644
      with_items:
        - build
    - name: Add PATH into bashrc
      lineinfile:
        dest="/home/{{ item }}/.bashrc"
        line="export PATH=$PATH:$HADOOP_HOME/bin"
        state=present
        owner={{ item }}
        mode=0644
      with_items:
        - build
    - name: Copy config files
      copy: src=etc/hadoop/{{ item }} dest=/usr/local/hadoop/etc/hadoop/{{ item }}
      with_items:
        - core-site.xml
        - hadoop-env.sh 
        - hdfs-site.xml
        - yarn-env.sh
        - yarn-site.xml
