- hosts: All #Sample
  remote_user: ubuntu
  become: True
  become_method: sudo
  become_user: root
  gather_facts: force
  tasks:
    - name: Install Storm
      script: util/storm.sh
    - name: Add Storm HOME into bashrc
      lineinfile:
        dest="/home/{{ item }}/.bashrc"
        line="export STORM_HOME=/usr/local/storm"
        state=present
        owner={{ item }}
        mode=0644
      with_items:
        - ubuntu
    - name: Add PATH into bashrc
      lineinfile:
        dest="/home/{{ item }}/.bashrc"
        line="export PATH=$PATH:$STORM_HOME/bin"
        state=present
        owner={{ item }}
        mode=0644
      with_items:
        - ubuntu
