- hosts: All #Sample
  remote_user: ubuntu
  become: True
  become_method: sudo
  become_user: root
  gather_facts: force
  tasks:
    - name: Install Spark
      script: util/spark.sh
    - name: Add Spark HOME into bashrc
      lineinfile:
        dest="/home/{{ item }}/.bashrc"
        line="export SPARK_HOME=/usr/local/spark"
        state=present
        owner={{ item }}
        mode=0644
      with_items:
        - ubuntu
    - name: Add PATH into bashrc
      lineinfile:
        dest="/home/{{ item }}/.bashrc"
        line="export PATH=$PATH:$SPARK_HOME/bin"
        state=present
        owner={{ item }}
        mode=0644
      with_items:
        - ubuntu
