- hosts: All #Sample
  remote_user: ubuntu
  become: True
  become_method: sudo
  become_user: root
  gather_facts: force
  tasks:
    - name: Install Pig
      script: util/pig.sh
    - name: Add Pig HOME into bashrc
      lineinfile:
        dest="/home/{{ item }}/.bashrc"
        line="export PIG_HOME=/usr/local/pig"
        state=present
        owner={{ item }}
        mode=0644
      with_items:
        - ubuntu
    - name: Add PATH into bashrc
      lineinfile:
        dest="/home/{{ item }}/.bashrc"
        line="export PATH=$PATH:$PIG_HOME/bin"
        state=present
        owner={{ item }}
        mode=0644
      with_items:
        - ubuntu
